name: Deploy to EC2

on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Copy code to EC2
      uses: appleboy/scp-action@v1
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: ./
          target: ./

    - name: copy index file to nginx folder
      uses: appleboy/ssh-action@v1
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            ls -al
            pwd
            sudo cp -r * /var/www/html
            sudo systemctl restart nginx


